#!/bin/bash

#pm2 start games/gamee.py --interpreter venv/bin/python3 --name Gamee:1 -- Gamee:1 && \
#pm2 start games/gamee.py --interpreter venv/bin/python3 --name Gamee:2 -- Gamee:2 && \
#pm2 start games/gamee.py --interpreter venv/bin/python3 --name Gamee:3 -- Gamee:3 && \
#pm2 start games/gamee.py --interpreter venv/bin/python3 --name Gamee:4 -- Gamee:4 && \
pm2 start games/cold.py --interpreter venv/bin/python3 --name BNB-Cold_1 -- BNB-Cold_1 && \
pm2 start games/cold.py --interpreter venv/bin/python3 --name BNB-Cold_2 -- BNB-Cold_2 && \
pm2 start games/cold.py --interpreter venv/bin/python3 --name BNB-Cold_3 -- BNB-Cold_3 && \
pm2 start games/cold.py --interpreter venv/bin/python3 --name BNB-Cold_4 -- BNB-Cold_4 && \
pm2 start games/lumcity-autoupgrade.py --interpreter venv/bin/python3 --name LumCity-Auto_1 -- LumCity-Auto_1 && \
pm2 start games/lumcity-autoupgrade.py --interpreter venv/bin/python3 --name LumCity-Auto_2 -- LumCity-Auto_2 && \
pm2 start games/lumcity-autoupgrade.py --interpreter venv/bin/python3 --name LumCity-Auto_3 -- LumCity-Auto_3 && \
pm2 start games/lumcity-autoupgrade.py --interpreter venv/bin/python3 --name LumCity-Auto_4 -- LumCity-Auto_4 && \
pm2 start games/hot.py --interpreter venv/bin/python3 --name HOT_1 -- HOT_1 && \
pm2 start games/hot.py --interpreter venv/bin/python3 --name HOT_2 -- HOT_2 && \
pm2 start games/hot.py --interpreter venv/bin/python3 --name HOT_3 -- HOT_3 && \
pm2 start games/hot.py --interpreter venv/bin/python3 --name HOT_4 -- Seed_4 && \
pm2 start games/seed.py --interpreter venv/bin/python3 --name Seed_1 -- Seed_1 && \
pm2 start games/seed.py --interpreter venv/bin/python3 --name Seed_2 -- Seed_2 && \
pm2 start games/seed.py --interpreter venv/bin/python3 --name Seed_3 -- Seed_3 && \
pm2 start games/seed.py --interpreter venv/bin/python3 --name Seed_4 -- Seed_4 && \
pm2 start games/vertus.py --interpreter venv/bin/python3 --name Vertus_1 -- Vertus_1 && \
pm2 start games/vertus.py --interpreter venv/bin/python3 --name Vertus_2 -- Vertus_2 && \
pm2 start games/vertus.py --interpreter venv/bin/python3 --name Vertus_3 -- Vertus_3 && \
pm2 start games/vertus.py --interpreter venv/bin/python3 --name Vertus_4 -- Vertus_4 && \
pm2 start games/wave.py --interpreter venv/bin/python3 --name Wave_1 -- Wave_1 && \
pm2 start games/wave.py --interpreter venv/bin/python3 --name Wave_2 -- Wave_2 && \
pm2 start games/wave.py --interpreter venv/bin/python3 --name Wave_3 -- Wave_3 && \
pm2 start games/wave.py --interpreter venv/bin/python3 --name Wave_4 -- Wave_4 && \
pm2 start games/timefarm-autostake.py --interpreter venv/bin/python3 --name TimeFarm-AutoStake_1 -- TimeFarm-AutoStake_1 && \
pm2 start games/timefarm-autostake.py --interpreter venv/bin/python3 --name TimeFarm-AutoStake_2 -- TimeFarm-AutoStake_2 && \
pm2 start games/timefarm-autostake.py --interpreter venv/bin/python3 --name TimeFarm-AutoStake_3 -- TimeFarm-AutoStake_3 && \
pm2 start games/timefarm-autostake.py --interpreter venv/bin/python3 --name TimeFarm-AutoStake_4 -- TimeFarm-AutoStake_4 && \
pm2 start games/simpletap.py --interpreter venv/bin/python3 --name SimpleTap_1 -- SimpleTap_1 && \
pm2 start games/simpletap.py --interpreter venv/bin/python3 --name SimpleTap_2 -- SimpleTap_2 && \
pm2 start games/simpletap.py --interpreter venv/bin/python3 --name SimpleTap_3 -- SimpleTap_3 && \
pm2 start games/simpletap.py --interpreter venv/bin/python3 --name SimpleTap_4 -- SimpleTap_4 && \
pm2 start games/tabizoo-autoupgrade.py --interpreter venv/bin/python3 --name TabiZoo-AutoUpgrade_1 -- TabiZoo-AutoUpgrade_1 && \
pm2 start games/tabizoo-autoupgrade.py --interpreter venv/bin/python3 --name TabiZoo-AutoUpgrade_2 -- TabiZoo-AutoUpgrade_2 && \
pm2 start games/tabizoo-autoupgrade.py --interpreter venv/bin/python3 --name TabiZoo-AutoUpgrade_3 -- TabiZoo-AutoUpgrade_3 && \
pm2 start games/tabizoo-autoupgrade.py --interpreter venv/bin/python3 --name TabiZoo-AutoUpgrade_4 -- TabiZoo-AutoUpgrade_4 && \
pm2 start games/pixeltap.py --interpreter venv/bin/python3 --name PixelTap_1 -- PixelTap_1 && \
pm2 start games/pixeltap.py --interpreter venv/bin/python3 --name PixelTap_2 -- PixelTap_2 && \
pm2 start games/pixeltap.py --interpreter venv/bin/python3 --name PixelTap_3 -- PixelTap_3 && \
pm2 start games/pixeltap.py --interpreter venv/bin/python3 --name PixelTap_4 -- PixelTap_4 && \
pm2 start games/oxygen-autoupgrade.py --interpreter venv/bin/python3 --name Oxygen-Auto_1 -- Oxygen-Auto_1 && \
pm2 start games/oxygen-autoupgrade.py --interpreter venv/bin/python3 --name Oxygen-Auto_2 -- Oxygen-Auto_2 && \
pm2 start games/oxygen-autoupgrade.py --interpreter venv/bin/python3 --name Oxygen-Auto_3 -- Oxygen-Auto_3 && \
pm2 start games/oxygen-autoupgrade.py --interpreter venv/bin/python3 --name Oxygen-Auto_4 -- Oxygen-Auto_4 && \
pm2 start games/hexacore-autoupgrade.py --interpreter venv/bin/python3 --name Hexacore-Auto_1 -- Hexacore-Auto_1 && \
pm2 start games/hexacore-autoupgrade.py --interpreter venv/bin/python3 --name Hexacore-Auto_2 -- Hexacore-Auto_2 && \
pm2 start games/hexacore-autoupgrade.py --interpreter venv/bin/python3 --name Hexacore-Auto_3 -- Hexacore-Auto_3 && \
pm2 start games/mdao-autoupgrade.py --interpreter venv/bin/python3 --name MDAO-Auto_1 -- MDAO-Auto_1 && \
pm2 start games/mdao-autoupgrade.py --interpreter venv/bin/python3 --name MDAO-Auto_2 -- MDAO-Auto_2 && \
pm2 start games/iceberg.py --interpreter venv/bin/python3 --name Iceberg_1 -- Iceberg_1 && \
pm2 start games/iceberg.py --interpreter venv/bin/python3 --name Iceberg_2 -- Iceberg_2 && \
pm2 start games/iceberg.py --interpreter venv/bin/python3 --name Iceberg_3 -- Iceberg_3 && \
pm2 start games/iceberg.py --interpreter venv/bin/python3 --name Iceberg_4 -- Iceberg_4